version: '3.4'

services:
  db:
        image: mysql/mysql-server:5.7
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            42333:3306

  storecore.backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
